2021-07-17 12:44:50,969 INFO    MainThread:2444 [wandb_setup.py:_flush():69] setting env: {}
2021-07-17 12:44:50,970 INFO    MainThread:2444 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-17 12:44:50,970 INFO    MainThread:2444 [wandb_init.py:_log_setup():337] Logging user logs to C:\Users\Qiandehou\Desktop\github\pytorch_and_something\SIIM_FISABIO_RSNA_COVID_19_Detection\wandb\run-20210717_124450-26c3313t\logs\debug.log
2021-07-17 12:44:50,970 INFO    MainThread:2444 [wandb_init.py:_log_setup():338] Logging internal logs to C:\Users\Qiandehou\Desktop\github\pytorch_and_something\SIIM_FISABIO_RSNA_COVID_19_Detection\wandb\run-20210717_124450-26c3313t\logs\debug-internal.log
2021-07-17 12:44:50,972 INFO    MainThread:2444 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000019951373BE0>
2021-07-17 12:44:50,981 INFO    MainThread:2444 [wandb_init.py:init():370] calling init triggers
2021-07-17 12:44:50,981 INFO    MainThread:2444 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2021-07-17 12:44:50,981 INFO    MainThread:2444 [wandb_init.py:init():419] starting backend
2021-07-17 12:44:50,982 INFO    MainThread:2444 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-07-17 12:44:50,993 INFO    MainThread:2444 [backend.py:ensure_launched():135] starting backend process...
2021-07-17 12:44:51,044 INFO    MainThread:2444 [backend.py:ensure_launched():139] started backend process with pid: 17840
2021-07-17 12:44:51,045 INFO    MainThread:2444 [wandb_init.py:init():424] backend started and connected
2021-07-17 12:44:51,046 INFO    MainThread:2444 [wandb_run.py:_label_probe_notebook():844] probe notebook
2021-07-17 12:44:51,047 INFO    MainThread:2444 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-07-17 12:44:51,047 INFO    MainThread:2444 [wandb_init.py:init():472] updated telemetry
2021-07-17 12:44:51,048 INFO    MainThread:2444 [wandb_init.py:init():491] communicating current version
2021-07-17 12:44:56,053 INFO    MainThread:2444 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-17 12:44:58,145 INFO    MainThread:2444 [wandb_init.py:init():529] starting run threads in backend
2021-07-17 12:45:03,161 INFO    MainThread:2444 [wandb_run.py:_console_start():1623] atexit reg
2021-07-17 12:45:03,162 INFO    MainThread:2444 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.WRAP
2021-07-17 12:45:03,163 INFO    MainThread:2444 [wandb_run.py:_redirect():1534] Wrapping output streams.
2021-07-17 12:45:03,164 INFO    MainThread:2444 [wandb_run.py:_redirect():1558] Redirects installed.
2021-07-17 12:45:03,164 INFO    MainThread:2444 [wandb_init.py:init():554] run started, returning control to user process
2021-07-17 12:45:43,585 INFO    MainThread:2444 [wandb_init.py:_pause_backend():250] pausing backend
2021-07-17 12:45:43,585 INFO    MainThread:2444 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-07-17 12:46:06,341 INFO    MainThread:2444 [wandb_init.py:_resume_backend():259] resuming backend
2021-07-17 12:46:12,912 INFO    MainThread:2444 [wandb_setup.py:_flush():69] setting env: {}
2021-07-17 12:46:12,912 INFO    MainThread:2444 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-17 12:46:12,913 INFO    MainThread:2444 [wandb_init.py:_log_setup():337] Logging user logs to C:\Users\Qiandehou\Desktop\github\pytorch_and_something\SIIM_FISABIO_RSNA_COVID_19_Detection\wandb\run-20210717_124612-ln42ztwo\logs\debug.log
2021-07-17 12:46:12,913 INFO    MainThread:2444 [wandb_init.py:_log_setup():338] Logging internal logs to C:\Users\Qiandehou\Desktop\github\pytorch_and_something\SIIM_FISABIO_RSNA_COVID_19_Detection\wandb\run-20210717_124612-ln42ztwo\logs\debug-internal.log
2021-07-17 12:46:12,915 INFO    MainThread:2444 [wandb_init.py:init():370] calling init triggers
2021-07-17 12:46:12,917 INFO    MainThread:2444 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2021-07-17 12:46:12,917 INFO    MainThread:2444 [wandb_init.py:init():390] re-initializing run, found existing run on stack: 26c3313t
2021-07-17 12:46:12,917 INFO    MainThread:2444 [wandb_run.py:finish():1293] finishing run poi/pytorch_and_something/26c3313t
